GET http://localhost:3001/todos


###


POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Swim"
}


###

DELETE http://localhost:3001/todo/delete/629ba9efdea7e69eebca0b77


###


PATCH http://localhost:3001/todo/complete/629d4c5ebb7a2039d0f7fbdd