GET http://localhost:3000/todos


###


POST http://localhost:3000/todo/new
Content-Type: application/json

{
    "text": "Run"
}


###

DELETE http://localhost:3000/todo/delete/629ba9f6dea7e69eebca0b7a


###


PATCH http://localhost:3000/todo/complete/629d4c5ebb7a2039d0f7fbdd