GET http://localhost:3000/todos


###


POST http://localhost:3000/todo/new
Content-Type: application/json

{
    "text": "Drive"
}


###

DELETE http://localhost:3000/todo/delete/6299432563b12229fc47a1dc